name: Build

on:
  push:
    branches: [ "develop, ft-simulate-bus-motion-14"]
  pull_request:
    branches: [ "develop, ft-simulate-bus-motion-14"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build